# -*- coding: utf-8 -*-
"""Fake job posting Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJZV5x_Ct20HYzYPoHOlb-Ul7EeRl1Nt

**1. Import Libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import re
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

import warnings
warnings.filterwarnings('ignore')

import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

"""**2. Load Dataset**"""

import pandas as pd

df = pd.read_csv(
    '/content/fake_job_postings.csv',
    engine='python',
    on_bad_lines='skip'
)

print(df.shape)
df.head()

"""**3. Basic EDA**"""

print("\nFraudulent distribution:")
print(df['fraudulent'].value_counts(normalize=True))

# Highly imbalanced → we will use class_weight later
plt.figure(figsize=(6,4))
sns.countplot(x='fraudulent', data=df)
plt.title('Real vs Fraudulent Job Postings')
plt.show()

"""**4. Select Relevant Columns**"""

text_columns = ['title', 'company_profile', 'description', 'requirements', 'benefits']

cat_columns = ['location', 'department', 'salary_range', 'employment_type',
               'required_experience', 'required_education', 'industry', 'function']

binary_columns = ['telecommuting', 'has_company_logo', 'has_questions']

for col in text_columns:
    df[col] = df[col].fillna('')

df['full_text'] = df[text_columns].agg(' '.join, axis=1)

for col in cat_columns:
    df[col] = df[col].fillna('missing')

for col in binary_columns:
    df[col] = df[col].fillna(0)

"""**5. NLP Preprocessing Function**"""

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    # Lowercase
    text = text.lower()

    # Remove HTML tags
    text = re.sub(r'<[^>]+>', ' ', text)

    # Remove URLs
    text = re.sub(r'http[s]?://\S+', ' ', text)

    # Remove email addresses
    text = re.sub(r'\S+@\S+', ' ', text)

    # Remove punctuation and numbers
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Tokenize
    tokens = word_tokenize(text)

    # Remove stopwords and lemmatize
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words and len(word) > 2]

    return ' '.join(tokens)

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
# Apply cleaning
print("Cleaning text...")
df['cleaned_text'] = df['full_text'].apply(clean_text)
print("Text cleaning completed.")

X_text = df['cleaned_text']
X_cat = df[cat_columns + binary_columns]
y = df['fraudulent']

"""**7. TF-IDF Vectorization for Text (max_features=5000 to avoid memory issues)**"""

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.95
)

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.95
)

"""**8. Split Data**"""

X_text_train, X_text_test, X_cat_train, X_cat_test, y_train, y_test = train_test_split(
    X_text, X_cat, y, test_size=0.2, random_state=42, stratify=y
)

# Transform text
X_text_train_tfidf = tfidf.fit_transform(X_text_train)
X_text_test_tfidf = tfidf.transform(X_text_test)

# Transform categorical + binary features
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=True), cat_columns),
        ('binary', 'passthrough', binary_columns)
    ]
)

X_cat_train_processed = preprocessor.fit_transform(X_cat_train)
X_cat_test_processed = preprocessor.transform(X_cat_test)

"""**9. Combine TF-IDF + Categorical Features (Sparse Matrix → Dense for Keras)**"""

from scipy.sparse import hstack

X_train = hstack([X_text_train_tfidf, X_cat_train_processed])
X_test = hstack([X_text_test_tfidf, X_cat_test_processed])

# Convert to dense
X_train_dense = X_train.toarray()
X_test_dense = X_test.toarray()

print("Final feature matrix shape:", X_train_dense.shape)

from sklearn.utils.class_weight import compute_class_weight

classes = np.unique(y_train)
class_weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)
class_weight_dict = dict(zip(classes, class_weights))
print("Class weights:", class_weight_dict)

model = Sequential([
    Dense(512, activation='relu', input_shape=(X_train_dense.shape[1],)),
    Dropout(0.4),
    Dense(256, activation='relu'),
    Dropout(0.4),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy', 'Precision', 'Recall']
)

model.summary()

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history = model.fit(
    X_train_dense, y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=64,
    class_weight=class_weight_dict,
    callbacks=[early_stop],
    verbose=1
)

from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

y_pred_prob = model.predict(X_test_dense)
y_pred = (y_pred_prob > 0.5).astype(int).flatten()

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("ROC AUC Score:", roc_auc_score(y_test, y_pred_prob))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

model.save('fraudulent_job_model.keras')
import joblib
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')
joblib.dump(preprocessor, 'categorical_preprocessor.pkl')

print("Model and preprocessors saved!")

test_job = {
    'title': 'Data Entry Clerk - Work From Home $5000/week',
    'location': 'missing',
    'department': 'missing',
    'salary_range': 'missing',
    'company_profile': '',
    'description': 'Easy job! Just enter data from home and get paid big money every week. No experience needed.',
    'requirements': 'Must have computer and internet. Small registration fee to start.',
    'benefits': 'Unlimited earning potential! Be your own boss!',
    'telecommuting': 1,
    'has_company_logo': 0,
    'has_questions': 0,
    'employment_type': 'missing',
    'required_experience': 'missing',
    'required_education': 'missing',
    'industry': 'missing',
    'function': 'missing'
}

# Prediction function (uses already loaded model, tfidf, preprocessor)
def predict_single_job(job_dict):
    df_new = pd.DataFrame([job_dict])

    # Fill missing columns safely
    for col in text_columns:
        df_new[col] = df_new.get(col, '').fillna('')
    for col in cat_columns:
        df_new[col] = df_new.get(col, 'missing').fillna('missing')
    for col in binary_columns:
        df_new[col] = df_new.get(col, 0).fillna(0)

    # Combine and clean text
    df_new['full_text'] = df_new[text_columns].agg(' '.join, axis=1)
    df_new['cleaned_text'] = df_new['full_text'].apply(clean_text)

    # Vectorize
    text_vec = tfidf.transform(df_new['cleaned_text'])
    cat_vec = preprocessor.transform(df_new[cat_columns + binary_columns])
    X_new = hstack([text_vec, cat_vec]).toarray()

    # Predict
    prob = model.predict(X_new, verbose=0)[0][0]
    prediction = 'FRAUDULENT ⚠️' if prob > 0.5 else 'REAL ✅'

    return prob, prediction

# Run prediction
probability, result = predict_single_job(test_job)

print("\n=== SINGLE SAMPLE PREDICTION ===\n")
print(f"Job Title: {test_job['title']}")
print(f"Fraud Probability: {probability:.4f}")
print(f"Final Prediction : {result}")

if probability > 0.5:
    print("\n🚨 This job posting looks highly suspicious / likely fake!")
else:
    print("\n✅ This job posting appears legitimate.")